### PR TITLE
Sub-items / relatively positioned windows

### PR DESCRIPTION
**Pull request by redhog**
* [X] A window can reference other windows to be drawn at the same time as iteself
* [x] Such windows are positioned relative to the main window
* [ ] Such windows have access to properties of the main window

### CODE REVIEW

**Comment by redhog** [comment]
This is a workaround for https://github.com/redhog/InfiniteGlass/issues/51

**Comment by BackOrder** [comment]
```
Successfully built 0ca989a2cd2d
Successfully tagged redhogorg/glass:0.0.2
su: System error
```

uh?

**Comment by BackOrder** [comment]
I really don't know what happened. Master builds and run without problems but the branch ig-item won't. Keep getting the "su: System error". Then running `docker run -it redhogorg/glass:0.0.2` ends up with....

```
Xephyr cannot open host display. Is DISPLAY set?
xinit: giving up
xinit: unable to connect to X server: Cannot assign requested address
xinit: server error
Makefile:47: recipe for target 'run' failed
make: *** [run] Error 1
```

**Comment by BackOrder** [comment]
Update. Tried the full command line directly, seems to be working. Though I'm not seeing any window decorations. Why does it work with the command line but not the bash script... mystery?

```
  docker run \
          --name glass \
          -m 2gb \
          -ti \
          --ipc=host \
          -v ~/.config/glass:/home/glass/.config/glass \
          -v /tmp/.X11-unix:/tmp/.X11-unix \
          -v /tmp/.docker.xauth:/tmp/.docker.xauth \
          -e XAUTHORITY=/tmp/.docker.xauth \
          -e DISPLAY=:0 \
          $IMAGE
```

**Comment by BackOrder** [comment]
```
 bash -x ./scripts/run-in-docker.sh
+ IMAGE=redhogorg/glass:0.0.2
+ '[' '' == clean ']'
++ docker images -q redhogorg/glass:0.0.2
+ '[' dccbd993e2b8 == '' ']'
+ mkdir -p /home/ian/.config/glass
+ xauth nlist :0
+ sed -e 's/^..../ffff/'
++ docker ps -a -q -f name=glass
+ '[' '!' 0d6fd1d92d0a ']'
+ docker start -a -i glass
su: System error
```

**Comment by BackOrder** [comment]
Completely removed docker.

Reinstalled docker.

Victory.

**Pull request merged**
